# Generated by Django 5.1.3 on 2026-01-28 17:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_accident_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accident',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Accident Record', 'verbose_name_plural': 'Accident Records'},
        ),
        migrations.AlterModelOptions(
            name='videosession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Session', 'verbose_name_plural': 'Video Sessions'},
        ),
        migrations.RenameField(
            model_name='videosession',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='videosession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='location',
            field=models.CharField(default='Road - Unknown', help_text='Camera location or road name', max_length=100),
        ),
        migrations.AddField(
            model_name='videosession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='video_id',
            field=models.CharField(default='video_001', help_text='Unique video identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='accident',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Detection confidence percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='accident',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details', null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accident',
            name='image',
            field=models.ImageField(help_text='Captured frame of the accident', upload_to='accident_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Confirmed after multi-frame analysis'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='location',
            field=models.CharField(default='Road - Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='accident',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle_count',
            field=models.IntegerField(default=1, help_text='Number of vehicles detected'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='video_id',
            field=models.CharField(default='video_001', max_length=100),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='filename',
            field=models.CharField(help_text='Original video filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='video_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['-timestamp'], name='detection_a_timesta_e61011_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['location'], name='detection_a_locatio_7e1738_idx'),
        ),
    ]
