# Generated by Django 6.0.3 on 2026-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_accident_options_alter_videosession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='alert_sent',
            field=models.BooleanField(default=False, help_text='Whether alert has been sent'),
        ),
        migrations.AddField(
            model_name='videosession',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether video has been processed'),
        ),
    ]
